name: libpythonproVelton-CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.0
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.0'
    - name: cp contrib/env-sample .env
      run: |
        cp contrib/env-sample .evn
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install pipenv
        pipenv install codecov
        pipenv sync -d
        pipenv install --deploy --dev

    - name: Test with pytest
